language: node_js
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 9
- 8
- 10
before_install:
  - yarn global add greenkeeper-lockfile@1
  - curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash
before_script:
  - greenkeeper-lockfile-update
  - cd src/ && fossa
script:
- yarn build
- if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn poi build; fi

deploy:
  provider: pages
  skip-cleanup: false
  github-token: "$GH_TOKEN"
  local-dir: docs
  on:
    branch: master

after_success:
- greenkeeper-lockfile-upload
- if [[ $TRAVIS_BRANCH == 'master' ]]; then yarn travis-deploy-once "yarn semantic-release"; fi
